security:
  oauth2:
    client:
      client-id: testAppId2
      client-secret: testSecert2
      user-authorization-uri: http://127.0.0.1:9999/server/oauth/authorize
      access-token-uri: http://127.0.0.1:9999/server/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:9999/server/oauth/token_key
server:
  port: 8081
  context-path: /client-b
